### ISSUE TITLE
Request-URI Too Large error after viewing 20 items.

### ISSUE THREAD

**Issue by stepheneb** [provideal/tabulatr#11]
Create and startup the tabulatr-demo: https://github.com/provideal/tabulatr-demo
- Select http://127.0.0.1:3000/products/index_fancy
- select 20 items per page and apply
- select _Select All_
- select _Select None_

WEBrick reports:

```
Completed 200 OK in 228ms (Views: 101.4ms | ActiveRecord: 3.6ms)
[2011-04-12 16:13:35] ERROR WEBrick::HTTPStatus::RequestURITooLarge
```

The URI appears to be about 1402 chars.

At this point any change in the _fancy_ table throws this error.

Here's what the query params look like:

```
product_reset_state:Reset
product_pagination%5Bcurrent_page%5D:1
product_pagination%5Bpage%5D:1
product_pagination%5Bpagesize%5D:20
ping:pong
product_checked%5Bchecked_ids%5D:IdS5j6n
product_checked%5Bvisible%5D:IdS58ce7ti8x6b
product_filter%5Btitle%5D%5Blike%5D:
product_filter%5Bprice%5D%5Bfrom%5D:
product_filter%5Bprice%5D%5Bto%5D:
product_filter%5Bactive%5D:
product_filter%5Bdescription%5D%5Blike%5D:
product_filter%5B__association%5D%5Bvendor.id%5D:
product_filter%5B__association%5D%5Btags.title%5D:
product_checked%5Bcurrent_page%5D%5B%5D:1
product_checked%5Bcurrent_page%5D%5B%5D:2
product_checked%5Bcurrent_page%5D%5B%5D:3
product_checked%5Bcurrent_page%5D%5B%5D:4
product_checked%5Bcurrent_page%5D%5B%5D:5
product_checked%5Bcurrent_page%5D%5B%5D:6
product_checked%5Bcurrent_page%5D%5B%5D:7
product_checked%5Bcurrent_page%5D%5B%5D:8
product_checked%5Bcurrent_page%5D%5B%5D:9
product_checked%5Bcurrent_page%5D%5B%5D:10
product_checked%5Bcurrent_page%5D%5B%5D:11
product_checked%5Bcurrent_page%5D%5B%5D:12
product_checked%5Bcurrent_page%5D%5B%5D:13
product_checked%5Bcurrent_page%5D%5B%5D:14
product_checked%5Bcurrent_page%5D%5B%5D:15
product_checked%5Bcurrent_page%5D%5B%5D:16
product_checked%5Bcurrent_page%5D%5B%5D:17
product_checked%5Bcurrent_page%5D%5B%5D:18
product_checked%5Bcurrent_page%5D%5B%5D:19
product_checked%5Bcurrent_page%5D%5B%5D:20
```

Also the _dummy_app_session cookie is about 1953 chars -- this may well not be a problem but I noticed it while looking at the URI issue.

**Comment by provideal** [comment]
Hi stepheneb,

I know. This is a problem with WEBrick only, so if you're not deploying with WEBrick, this is no problem. 

We intentionally decided to put everything into GET parameters 'cause using POST would clash with the default routes, and you can paste a URI to your current view, which may be handy.

We should absolutely document this issue in the README.

Thanks four your feedback!
