### ISSUE TITLE
Feature: i18n lookup for attribute names

### ISSUE THREAD

**Issue by zealot128** [provideal/tabulatr#13]
nice plugin.
Unfortunately I have to add a:

```
t.column :published, :header => t("activerecord.attributes.post.published")  
```

ActiveRecord Lookup Path to each attribute to ensure a correctly translated attribute name. Is it possibile to look that by default, like formtastic/rails default forms automatically do that? This would play very nicely altogether with i18n.

**Comment by Crunch09** [comment]
Hi @zealot128 , if you are still interested [tabulatr2](https://github.com/provideal/tabulatr2) got you covered, attribute names are automatically translated.
