### ISSUE TITLE
Potential to read name wrong

### ISSUE THREAD

**Issue by krisleech** [provideal/tabulatr#14]
I read the name as tabular, not tabulatr, and it appears there is a gem with the name tabular so bunder was happy. However when I tried to use tabulatr the rake task didn't work and AR didn't have the find_for_table method... 

This may just be my haste and eye sight, but it might be worth highlighting the name in the README.

**Comment by dmasur** [comment]
I run into the same name thing. maybe a renaming would be usefull.

**Comment by provideal** [comment]
Hey Folks, I see the point, but I hesitate to change the name... 
So I added a note on the spelling in the Readme.
