### ISSUE TITLE
Add the `dom_id` to each table row

### ISSUE THREAD

**Issue by sterrym** [provideal/tabulatr#17]
eg:. Instead of just "&lt;tr&gt;&lt;td&gt;...&lt;/td&gt;&lt;/tr&gt;", output  "&lt;tr id="product_1"&gt;&lt;td&gt;...&lt;/td&gt;&lt;/tr&gt;"
This is useful for CSS and for automated testing (rspec or cucumber), This also helps the library act similar to `content_tag_for`. 

See: https://github.com/sterrym/tabulatr/tree/row_ident

**Comment by provideal** [comment]
Thanks a lot! It's added in 0.2.0
