### ISSUE TITLE
Starterror with 0.2.0

### ISSUE THREAD

**Issue by dmasur** [provideal/tabulatr#19]
... tabulatr-0.2.0/lib/tabulatr/tabulatr/finder.rb:49: syntax error, unexpected '.', expecting kEND
 .split(Tabulatr.table_form_options[:checked_separator])

i run 1.8.7 with rails 3.1.0.rc1

**Comment by provideal** [comment]
Hi TBAA! I fixed that in the repo. Sadly, I got severe problems with rake that I'm unable to fix right now, so I refrain from pushing 0.2.1 to rubygems for now. So -- if you like -- you may try using tabulatr from git.
